version: '2'
services:
  catinymessenger-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra
    volumes:
      - /root/volumes/jhipster/CatinyMessenger/cassandra/:/var/lib/cassandra/data
  catinymessenger-cassandra-node:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra-node
    volumes:
      - /root/volumes/jhipster/CatinyMessenger/cassandra-node-1/:/var/lib/cassandra/data

  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra-migration
  catinymessenger-redis:
    extends:
      file: redis.yml
      service: catinymessenger-redis
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
